# Generated by Django 4.2.3 on 2025-08-09 17:40

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(default=main.models.generate_room_id, max_length=9, primary_key=True, serialize=False, unique=True)),
                ('rounds', models.IntegerField(default=3)),
                ('timer', models.IntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
