# Generated by Django 4.2.3 on 2025-08-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='currentEmoji',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='currentTurn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='gameState',
            field=models.CharField(default='waiting', max_length=20),
        ),
    ]
